---
title: Q
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
url: http://www.invisibleknight.ga/
theme_settings:
  title: Type Theme
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: 
  description: A website with blog posts and pages
  header_text: 
  header_text_feature_image: 
  footer_text: 'Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type
    Theme</a>

'
  rss: false
  email_address: 
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  gitlab: 
  github: 
  gitter: 
  google_plus: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  tumblr: 
  twitter: 
  wordpress: 
  youtube: 
  google_analytics: 
  disqus_shortname: 
  katex: true
  search: false
  str_follow_on: Follow on
  str_rss_follow: Follow RSS feed
  str_email: Email
  str_next_post: Next post
  str_previous_post: Previous post
  str_next_page: Next
  str_previous_page: Prev
  str_continue_reading: Continue reading
  str_javascript_required_disqus: Please enable JavaScript to view comments.
  str_search_no_results: No results found.
  google_fonts: Source+Sans+Pro:400,700,700italic,400italic
  post_navigation: false
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
